name: Build and Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STRAPI_URL: ${{ secrets.STRAPI_URL }}
      STORE_SLUG: ${{ secrets.STORE_SLUG }}
      BASE_URL: ${{ secrets.BASE_URL }}
      COLOR_PRIMARY: ${{ secrets.COLOR_PRIMARY }}
      COLOR_ACCENT: ${{ secrets.COLOR_ACCENT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Markket test
        run: npm run build
